config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'dashboard#index'

  resources :teams do
    resources :members
    resources :opponents
    resources :games
  end

end

app/models/game.rb
class Game < ActiveRecord::Base

  has_one :team

  before_update :set_game_result

  protected

    def set_game_result
      if self.points_for > self.points_against
        self.result = 1
      else 
        self. result = 2
      end
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  layout "team" 

  def index
    @team = Team.find(params[:team_id])
    @game = Game.new
  end

  def edit
    @team = Team.find(params[:team_id])
    @game = Game.where("team_id = ? AND id = ?", params[:team_id], params[:id]).first
  end

  def create
    game = Game.new(game_params)

    respond_to do |format|
      if game.save
        format.html { redirect_to team_games_path(params[:team_id]), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: game }
      else
        format.html { render :new }
        format.json { render json: game.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to team_games_path(params[:team_id]), notice: 'Game was successfully updated.' }
      end
    end
  end

  private

    def game_params
      params.require(:game).permit(:team_id, :opponent_id, :field, :park, :points_for, :points_against, :result, :year, :season)
    end

end

app/helpers/game_helper.rb
module GameHelper

  def game_result(game)
    if game == 1
      "Win"
    elsif game == 2
      "Loss"
    else
      ""
    end
  end

end

app/views/games/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <%= form_for [@team, @game] do |f| %>

        <div class="form-group row">
          <label for="example-text-input" class="col-2 col-form-label"><%= f.label :field %></label>
          <div class="col-10">
            <%= f.text_field :field, :required => true, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <label for="example-text-input" class="col-2 col-form-label"><%= f.label :park %></label>
          <div class="col-10">
            <%= f.text_field :park, :required => true, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <label for="example-text-input" class="col-2 col-form-label"><%= f.label :points_for %></label>
          <div class="col-10">
            <%= f.text_field :points_for, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <label for="example-text-input" class="col-2 col-form-label"><%= f.label :points_against %></label>
          <div class="col-10">
            <%= f.text_field :points_against, class: 'form-control' %>
          </div>
        </div>

        <%= f.submit "Save Game" %>

      <% end %>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="view-settings">
  <button><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit Schedule</button>
</div>

<div class="item-wrap">

    <% @team.games.each do |game| %>
      <div class="item">
        <div>
          4/26 @ 4:00 PM<br/>
          <%= game.park %> - Field <%= game.field %>
        </div>
        <div>
          Opponent Name
        </div>
        <div>
          <%= game_result(game.result) %><br/>
          <%= game.points_for %>-<%= game.points_against %>
        </div>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Edit
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to 'Edit', edit_team_game_path(@team, game), class: 'dropdown-item' %>
            <a class="dropdown-item" href="#">Delete</a>
          </div>
        </div>
      </div>
    <% end %>

</div>

<%= form_for [@team, @game] do |f| %>
<tr>
  <td></td>
  <td></td>
  <td><%= f.text_field :park, :required => true %></td>
  <td><%= f.text_field :field, :required => true %></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td>
    <%= f.hidden_field :team_id, value: @team.id %>
    <%= f.hidden_field :season, value: @team.season %>
    <%= f.hidden_field :year, value: @team.year %>
    <%= f.submit "Add Game" %>
  </td>
</tr>
<% end %>

app/views/games/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <%= form_for @game do |f| %>

        <div class="form-group row">
          <label for="example-text-input" class="col-2 col-form-label"><%= f.label :field %></label>
          <div class="col-10">
            <%= f.text_field :field, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <label for="example-text-input" class="col-2 col-form-label"><%= f.label :park %></label>
          <div class="col-10">
            <%= f.text_field :park, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <label for="example-text-input" class="col-2 col-form-label"><%= f.label :points_for %></label>
          <div class="col-10">
            <%= f.text_field :points_for, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <label for="example-text-input" class="col-2 col-form-label"><%= f.label :points_against %></label>
          <div class="col-10">
            <%= f.text_field :points_against, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <label for="example-text-input" class="col-2 col-form-label"><%= f.label :season %></label>
          <div class="col-10">
            <%= f.text_field :season, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <label for="example-text-input" class="col-2 col-form-label"><%= f.label :year %></label>
          <div class="col-10">
            <%= f.text_field :year, class: 'form-control' %>
          </div>
        </div>

        <%= f.submit "Create Team" %>

      <% end %>
    </div>
  </div>
</div>