config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'dashboard#index'

  resources :teams do
    resources :members
    resources :opponents
    resources :games
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TallyRec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
  <div class="main-nav">
    <div class="main-nav__header">
      <%= current_user.first_name %> <%= current_user.last_name %>
    </div>
    <div class="main-nav__divider">Blood, Sweat &amp; Beers</div>
    <div class="main-nav__current-team--nav">
      <%= link_to 'Dashboard', team_path(default_team.team_id), class: 'nav-link' %>
      <%= link_to 'Schedule', team_games_path(default_team.team_id), class: 'nav-link' %>
      <%= link_to 'Roster', team_members_path(default_team.team_id), class: 'nav-link' %>
    </div>
    <div class="main-nav__divider">Your Teams</div>
    <div class="main-nav__team-list">
      <% users_teams.each do |t| %>
        <%= link_to t.team.name, team_path(t.team_id), class: 'nav-link' %>
      <% end %>
      <%= link_to  new_team_path, class: 'nav-link' do %>
        <i class="fa fa-plus" aria-hidden="true"></i> 
        Add Team
      <% end %>
    </div>
    <div class="main-nav__divider">Settings</div>
    <div class="main-nav__settings">
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
      <% else %>
        <%= link_to('Login', new_user_session_path)  %>  
      <% end %>
    </div>
  </div>
  <% end %>
  <div class="main-content">
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/team.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TallyRec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
  <div class="main-nav">
    <div class="main-nav__header">
      <%= current_user.first_name %> <%= current_user.last_name %>
    </div>
    <div class="main-nav__divider"><%= @team.name %></div>
    <div class="main-nav__team-list">
      <% users_teams.each do |t| %>
        <%= link_to t.team.name, team_path(t.team_id), class: 'nav-link' %>
      <% end %>
      <%= link_to  new_team_path, class: 'nav-link' do %>
        <i class="fa fa-plus" aria-hidden="true"></i> 
        Add Team
      <% end %>
    </div>
    <div class="main-nav__divider">Settings</div>
    <div class="main-nav__settings">
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
      <% else %>
        <%= link_to('Login', new_user_session_path)  %>  
      <% end %>
    </div>
  </div>
  <% end %>
  <div class="main-content">
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <div class="team-dashboard">
      <p class="lead"><%= @team.name %></p>
      <p class="lead"><%= @team.season %> <%= @team.year %> <i class="fa fa-caret-down" aria-hidden="true"></i></p>
    </div>

    <div class="team-nav">
      <div class="team-nav--links">
        <%= link_to 'Dashboard', team_path(@team.id) %>
        <%= link_to 'Schedule', team_games_path(@team.id) %>
        <%= link_to 'Roster', team_members_path(@team.id) %>
        <a href="">Stats</a>
        <a href="">Messages</a>
      </div>
      <div class="team-nav--settings">
        <i class="fa fa-cog" aria-hidden="true"></i>
      </div>
    </div>
    <%= yield %>
  </div>
</body>
</html>